function add_row(){
    $rowno=$("#tramite .row").length;
    $rowno=$rowno+1;
    $("#tramite .row:last").after("<div class='row cuadro' id='row"+$rowno+"'> <div class='form-group col-sm-12'> <h5 class='book'> OFICINA </h5> <h5 class='book'> CUOF - ANEXO - UNGI </h5> <small>Oficina sobre la que solicita que se realice alguna gestión en SGT</small> </div><div class='form-group col-sm-3'> <label>Número</label> <input type='text' class='form-control' name='numeroOficina[]' placeholder='Número' id='numeroOficina'> </div><div class='form-group col-sm-9'> <label>Denominación</label> <input type='text' class='form-control' name='denominacionOficina[]' placeholder='Denominacion de Oficina' id='denominacionOficina'> </div><div class='form-group col-sm-12'> <h5 class='book'> GESTIÓN QUE SOLICITA </h5> <small>Seleccione la opción que requiera</small> </div><div class='form-group form-check col-sm-4'> <input class='form-check-input' type='radio' name='gestion"+$rowno+"[]' id='habilitar"+$rowno+"' value='habilitar'> <label class='form-check-label' for='habilitar"+$rowno+"'> Habilitar </label> </div><div class='form-group col-sm-8'> <select class='custom-select' name='solicita"+$rowno+"[]'> <option selected disabled>Categoria Solicitada</option> <option value='mes'>Mesa de Entrada y Salida</option> <option value='me'>Mesa de Entrada</option> <option value='ms'>Mesa de Salida</option> <option value='or'>Oficina de Registro</option> <option value='oso'>Oficina sin Operador</option> <option value='meso'>Mesa de Entrada sin Operador</option> </select> </div><div class='form-group form-check col-sm-4'> <input class='form-check-input' type='radio' name='gestion"+$rowno+"[]' id='modificar"+$rowno+"' value='modificar'> <label class='form-check-label' for='modificar"+$rowno+"'> Modificar Categoria </label> </div><div class='form-group col-sm-8'> <select class='custom-select' name='solicita"+$rowno+"[]'> <option selected disabled>Categoria Solicitada</option> <option value='mes'>Mesa de Entrada y Salida</option> <option value='me'>Mesa de Entrada</option> <option value='ms'>Mesa de Salida</option> <option value='or'>Oficina de Registro</option> <option value='oso'>Oficina sin Operador</option> <option value='meso'>Mesa de Entrada sin Operador</option> </select> </div><div class='form-group form-check col-sm-4'> <input class='form-check-input' type='radio' name='gestion"+$rowno+"[]' id='inhabilitar"+$rowno+"' value='inhabilitar'> <label class='form-check-label' for='inhabilitar"+$rowno+"'> Inhabilitar </label> </div><div class='form-group col-sm-8'> <input type='text' class='form-control' name='solicita"+$rowno+"[]' placeholder='CUOF'> <small> Especificar CUOF destino </small> </div><div class='form-group col-sm-12 text-right'> <button class='btn btn-outline-danger boton btn-sm' onclick=delete_row('row"+$rowno+"')> Borrar </button></div></div>");
    //$("#tramite .row:last").after("<tr id='row"+$rowno+"'><td><input type='text' name='name[]' placeholder='Enter Name'></td><td><input type='text' name='age[]' placeholder='Enter Age'></td><td><input type='text' name='job[]' placeholder='Enter Job'></td><td><input type='button' value='DELETE' onclick=delete_row('row"+$rowno+"')></td></tr>");
}

function delete_row(rowno){
    $('#'+rowno).remove();
}