function add_row(){
    $rowno=$("#tramite .row").length;
    $rowno=$rowno+1;
    $("#tramite .row:last").after("<div class='row cuadro' id='row"+$rowno+"'> <div class='form-group col-sm-2'> <label> D.N.I. </label> <input type='text' class='form-control' name='udni[]' placeholder='D.N.I.'> </div><div class='form-group col-sm-4'> <label> Apellido y Nombre </label> <input type='text' class='form-control' name='nomyape[]' placeholder='Apellido y Nombre'> </div><div class='form-group col-sm-2'> <label> Teléfono / Celular </label> <input type='text' class='form-control' name='tel[]' placeholder='Teléfono / Celular'> </div><div class='form-group col-sm-4'> <label> Correo Electrónico </label> <input type='email' class='form-control' name='email[]' placeholder='Correo Electrónico'> </div><div class='form-group col-sm-3'> <label> CUOF - ANEXO - UNGI </label> <input type='text' class='form-control' name='cuof[]' placeholder='CUOF - ANEXO - UNGI'> </div><div class='form-group col-sm-9'> <label> Denominación </label> <input type='text' class='form-control' name='udenominacion[]' placeholder='Denominación'> </div><div class='form-group col-sm-2 offset-sm-2'> <label> Solicita </label> <select class='custom-select' name='solicita[]'> <option selected disabled>Solicita</option> <option value='habilitar'>Habilitar</option> <option value='modificar'>Modificar</option> <option value='baja'>Baja</option> </select> </div><div class='form-group col-sm-2 offset-sm-4'> <label> Perfil </label> <select class='custom-select' name='perfil[]'> <option selected disabled>Perfil</option> <option value='consulta'>Consulta</option> <option value='operador'>Operador</option> </select> </div><div class='form-group col-sm-12 text-right'> <button class='btn btn-outline-danger boton btn-sm' onclick=delete_row('row"+$rowno+"')> Borrar </button></div></div>");
    //$("#tramite .row:last").after("<tr id='row"+$rowno+"'><td><input type='text' name='name[]' placeholder='Enter Name'></td><td><input type='text' name='age[]' placeholder='Enter Age'></td><td><input type='text' name='job[]' placeholder='Enter Job'></td><td><input type='button' value='DELETE' onclick=delete_row('row"+$rowno+"')></td></tr>");
}

function delete_row(rowno){
    $('#'+rowno).remove();
}